package env

const (
	ELASTICSEARCH_ENDPOINT = "ELASTICSEARCH_ENDPOINT"
	ELASTICSEARCH_PASSWORD = "ELASTICSEARCH_PASSWORD"

	ENV = "ENV"

	KUBECONFIG = "KUBECONFIG"

	DATABASE_SALT = "DATABASE_SALT"

	JWT_SECRET = "JWT_SECRET"

	REDIS_DSN = "REDIS_DSN"
	REDIS_AK  = "REDIS_AK"

	MYSQL_ADMIN_DSN = "MYSQL_ADMIN_DSN"
)
