package cons

const (
	ENV = "ENV"

	DEBUG = "DEBUG"

	KUBECONFIG = "KUBECONFIG"

	DATABASE_SALT = "DATABASE_SALT"

	JWT_SECRET = "JWT_SECRET"

	ELASTICSEARCH_PASSWORD = "ELASTICSEARCH_PASSWORD"
	ELASTICSEARCH_ENDPOINT = "ELASTICSEARCH_ENDPOINT"

	LOCAL_ELASTICSEARCH_ENDPOINT = "LOCAL_ELASTICSEARCH_ENDPOINT"

	REDIS_CLUSTER_DSN = "REDIS_CLUSTER_DSN"
	REDIS_DSN         = "REDIS_DSN"
	REDIS_AK          = "REDIS_AK"

	LOCAL_REDIS_CLUSTER_DSN = "LOCAL_REDIS_CLUSTER_DSN"
	LOCAL_REDIS_DSN         = "LOCAL_REDIS_DSN"
	LOCAL_REDIS_AK          = "LOCAL_REDIS_AK"

	MYSQL_ADMIN_DSN       = "MYSQL_ADMIN_DSN"
	LOCAL_MYSQL_ADMIN_DSN = "LOCAL_MYSQL_ADMIN_DSN"

	CloudflareAccountId    = "CLOUDFLARE_ACCOUNT_ID"
	CloudflareR2AccountKey = "CLOUDFLARE_R2_ACCOUNT_KEY"
	CloudflareR2AccountSK  = "CLOUDFLARE_R2_ACCOUNT_SK"

	KafkaUser     = "KAFKA_USER"
	KafkaPassword = "KAFKA_PASSWORD"

	RustFsEndpoint  = "RUST_FS_ENDPOINT"
	RustFsAccessKey = "RUST_FS_ACCESS_KEY"
	RustFsSecretKey = "RUST_FS_SECRET_KEY"

	MongoDSN = "MONGO_DSN"

	KookToken = "KOOK_TOKEN"

	Service = "SERVICE"
)
