package constant

const (
	ENV = "ENV"

	DEBUG = "DEBUG"

	KUBECONFIG = "KUBECONFIG"

	DATABASE_SALT = "DATABASE_SALT"

	JWT_SECRET = "JWT_SECRET"

	ELASTICSEARCH_PASSWORD = "ELASTICSEARCH_PASSWORD"
	ELASTICSEARCH_ENDPOINT = "ELASTICSEARCH_ENDPOINT"

	LOCAL_ELASTICSEARCH_ENDPOINT = "LOCAL_ELASTICSEARCH_ENDPOINT"

	REDIS_CLUSTER_DSN = "REDIS_CLUSTER_DSN"
	REDIS_DSN         = "REDIS_DSN"
	REDIS_AK          = "REDIS_AK"

	LOCAL_REDIS_CLUSTER_DSN = "LOCAL_REDIS_CLUSTER_DSN"
	LOCAL_REDIS_DSN         = "LOCAL_REDIS_DSN"
	LOCAL_REDIS_AK          = "LOCAL_REDIS_AK"

	MYSQL_ADMIN_DSN       = "MYSQL_ADMIN_DSN"
	LOCAL_MYSQL_ADMIN_DSN = "LOCAL_MYSQL_ADMIN_DSN"
)
